// Step 2: match the Commons title pool against every exercise name (+ the
// synonyms in synonyms.json) and write the reviewable list to
// docs/commons-candidates.md. A file matches when every (stemmed) word of the
// exercise name or a synonym appears in its title. Purely local: no network.
//
//   node scripts/commons/match.mjs
//
// Hand-checked outcomes live in data/verdicts.json and are shown in the list;
// licence/media details come from data/info.json (see info.mjs).
import fs from "node:fs";
import path from "node:path";
import { DATA, exercises, HERE, readJson, REPO, writeJson } from "./lib.mjs";

const pool = readJson(path.join(DATA, "pool.json"), { queries: {} });
const info = readJson(path.join(DATA, "info.json"), {});
const verdicts = readJson(path.join(DATA, "verdicts.json"), {});
const SYN = readJson(path.join(HERE, "synonyms.json"), {});
const categories = readJson(path.join(REPO, "src/data/exercises.json")).categories;

const STOP = new Set(["exercise", "exercises", "the", "and", "of", "a", "with", "for", "to", "on", "in", "program", "training"]);
const stem = (w) => w.replace(/(ings?|es|s)$/, "");
const words = (s) =>
  s.replace(/([a-z])([A-Z])/g, "$1 $2").toLowerCase().replace(/[^a-z0-9]+/g, " ").split(" ")
    .filter((w) => w && !STOP.has(w)).map(stem);
const bare = (t) => t.replace(/^File:/, "");

// Rank media kinds: animation > video > drawing > photo.
function kind(title) {
  const i = info[title];
  if (i?.mime === "image/gif") return i.duration > 0 ? "animation" : "drawing";
  if (i?.mime?.startsWith("video/") || i?.mime === "application/ogg") return "video";
  const ext = title.split(".").pop().toLowerCase();
  if (["webm", "ogv", "ogg", "mpg", "mp4"].includes(ext)) return "video";
  if (ext === "gif") return "gif";
  if (["svg", "png"].includes(ext)) return "drawing";
  if (["jpg", "jpeg", "webp", "tif", "tiff"].includes(ext)) return "photo";
  return "other";
}
const RANK = { animation: 5, gif: 4, video: 3, drawing: 2, photo: 1, other: 0 };

const titles = new Set(Object.values(pool.queries).flatMap((v) => v.titles));
// Titles that match by name but are clearly not exercise demonstrations.
const EXCLUDE = (verdicts._exclude || []).map((r) => new RegExp(r, "i"));
const titleWords = new Map(
  [...titles]
    .filter((t) => !/\.(pdf|djvu)$/i.test(t) && !EXCLUDE.some((r) => r.test(t)))
    .map((t) => [t, new Set(words(bare(t).replace(/\.[a-z0-9]+$/i, "")))]),
);

const matches = {};
for (const ex of exercises()) {
  const base = ex.title.replace(/\b(Exercises?|Program)\b/gi, "").trim();
  const phrases = [...new Set([base, ...(SYN[ex.slug] || [])].map((p) => p.toLowerCase()))];
  const hits = new Map();
  for (const p of phrases) {
    const pw = words(p);
    if (!pw.length) continue;
    for (const [t, tw] of titleWords) {
      if (!pw.every((w) => tw.has(w))) continue;
      const prev = hits.get(t);
      if (!prev || pw.length > prev.n) hits.set(t, { title: t, phrase: p, n: pw.length });
    }
  }
  matches[ex.slug] = [...hits.values()]
    .map((h) => ({ ...h, kind: kind(h.title) }))
    .sort((a, b) => RANK[b.kind] - RANK[a.kind] || b.n - a.n || a.title.localeCompare(b.title));
}
writeJson(path.join(DATA, "matches.json"), matches);

// ---- Markdown list -------------------------------------------------------
const MAX = 6;
const esc = (s) => s.replace(/\|/g, "\\|");
const link = (t) => `[${esc(bare(t))}](https://commons.wikimedia.org/wiki/${encodeURI(t.replace(/ /g, "_"))})`;
const lic = (t) => (info[t]?.license ? ` · ${info[t].license}` : "");
const counts = { used: 0, candidate: 0, rejected: 0, none: 0 };
const all = exercises();
const lines = [];
for (const c of categories) {
  lines.push(`\n## ${c.name}\n`, "| Exercise | Status | Commons matches (best first) |", "| --- | --- | --- |");
  for (const ex of all.filter((e) => e.categorySlug === c.slug)) {
    const m = matches[ex.slug];
    const v = verdicts[ex.slug];
    let status;
    if (ex.image) { status = "✅ In use"; counts.used++; }
    else if (v?.status === "rejected") { status = "❌ Checked — no match"; counts.rejected++; }
    else if (m.length) { status = "🔎 To check"; counts.candidate++; }
    else { status = "— None found"; counts.none++; }
    const shown = m.slice(0, MAX).map((h) => `${link(h.title)} (${h.kind}${lic(h.title)})`);
    if (m.length > MAX) shown.push(`+${m.length - MAX} more`);
    const note = ex.image
      ? `${ex.imageCredit?.author ?? ""} — \`${ex.image}\``
      : [v?.note, shown.join("<br>")].filter(Boolean).join("<br>");
    lines.push(`| ${esc(ex.title)} | ${status} | ${note || ""} |`);
  }
}

const header = `# Wikimedia Commons media — match list

Generated by \`node scripts/commons/match.mjs\` — do not edit by hand (edit
\`scripts/commons/data/verdicts.json\` or \`synonyms.json\` and re-run).

Every exercise was matched by name (and synonyms) against **${titles.size} Commons
files** gathered by \`scripts/commons/pool.mjs\`. A name match is only a
*candidate*: it must be checked visually against the exercise's own steps before
use, because a wrong demonstration is worse than none.

| | Exercises |
| --- | --- |
| ✅ In use | ${counts.used} |
| 🔎 Candidates to check | ${counts.candidate} |
| ❌ Checked — no usable match | ${counts.rejected} |
| — No name match on Commons | ${counts.none} |
| **Total** | **${all.length}** |

Kinds: *animation* (animated GIF), *video*, *gif* (GIF not yet inspected),
*drawing* (SVG/PNG still), *photo*. Most drawings come in numbered start/end
frames (e.g. \`… 1.svg\` / \`… 2.svg\`) that can be combined into a looping GIF.
`;
fs.mkdirSync(path.join(REPO, "docs"), { recursive: true });
fs.writeFileSync(path.join(REPO, "docs/commons-candidates.md"), header + lines.join("\n") + "\n");
console.log(counts, `pool ${titles.size} titles`);
